version: '3.8'

services:
  # api:
  #   build:
  #     context: backend
  #     dockerfile: backend.dockerfile
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - docker-compose.env
  #   depends_on:
  #     - db
  #   restart: unless-stopped

  db:
    image: postgres:14-alpine
    env_file:
      - docker-compose.env
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # web:
  #   build:
  #     context: frontend
  #     dockerfile: frontend.dockerfile
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - docker-compose.env

volumes:
  postgres_data:
