"""init tables

Revision ID: 81f50b577782
Revises: 
Create Date: 2024-04-17 09:05:13.898700+00:00

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81f50b577782"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("product_base_id", sa.String(), nullable=False),
        sa.Column("shop_base_id", sa.String(), nullable=False),
        sa.Column("platform_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("price_before_discount", sa.Integer(), nullable=True),
        sa.Column("rating_count", sa.Integer(), nullable=False),
        sa.Column("rating_avg", sa.Float(), nullable=False),
        sa.Column("comment_count", sa.Integer(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("url_thumbnail", sa.String(), nullable=False),
        sa.Column("url_images", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("historical_sold", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("product_base_id"),
    )
    op.create_table(
        "product_price_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_base_id", sa.String(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("price_ts", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_base_id"],
            ["product.product_base_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_price_insight",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_base_id", sa.String(), nullable=False),
        sa.Column("classify_price", sa.String(), nullable=True),
        sa.Column("current_price", sa.Integer(), nullable=False),
        sa.Column("ratio", sa.Integer(), nullable=False),
        sa.Column("max_price", sa.Integer(), nullable=False),
        sa.Column("min_price", sa.Integer(), nullable=False),
        sa.Column("delta_price", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_base_id"],
            ["product.product_base_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_review",
        sa.Column("review_base_id", sa.String(), nullable=False),
        sa.Column("product_base_id", sa.String(), nullable=False),
        sa.Column("platform_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column("images", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("created_at_platform", sa.BigInteger(), nullable=False),
        sa.Column("user_username", sa.String(), nullable=False),
        sa.Column("user_url_image", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_base_id"],
            ["product.product_base_id"],
        ),
        sa.PrimaryKeyConstraint("review_base_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_review")
    op.drop_table("product_price_insight")
    op.drop_table("product_price_history")
    op.drop_table("product")
    # ### end Alembic commands ###
